from pointcloud_localizer.synthetic import generate_scene, generate_default_mesh
from pointcloud_localizer.icp import icp
from pointcloud_localizer.evaluate import evaluate_registration, robustness_sweep